feat: implement public registry alias
CircleCI-Public/aws-ecr-orb pull request #235
Opened 2022-10-19 19:00 UTC by brivu

This `PR` implements the `public-registry-alias` parameter, enabling customers to push an image to a public `ecr` registry.

2022-10-19 19:02 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:f2317dbc9f4f60f14d71ac9115cf7041fff0780b

2022-10-19 19:08 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:04cc772cb9c80fb65dd6a2f0d47b026d621286e5

2022-10-19 19:12 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:8b2ea53b991039cca671f8585fc5225e4588755f

2022-10-19 19:23 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:510cbdd902833f3894864bbdc6f8beecc0dff587

2022-10-20 19:18 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:164967ac035a63bdf3fec83d58f275a4fbfc105a

2022-10-20 19:22 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:0a7c01f8e5f48ef693aab9180d88a95f76b14e31

2022-10-20 19:28 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:22368edca0cd39336927979b9d43d05b5844d693

2022-10-20 21:41 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:22368edca0cd39336927979b9d43d05b5844d693

2022-10-20 23:08 UTC, Jaryt requested changes
Looking good. Some small changes needed!

2022-10-20 23:08 UTC, Jaryt commented on .circleci/test-deploy.yml
> +  orb-tools: circleci/orb-tools@11.3
Orb tools is on .4 now :)

2022-10-20 23:08 UTC, Jaryt commented on src/commands/build-image.yml
> +        PARAM_PUBLIC_REGISTRY_ALIAS: <<parameters.public-registry-alias>>
Check out the Orb standards, we've defined them for parameter naming.

2022-10-21 20:22 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:a83d5142574ab57a7e38eaacf5552b0e7bee3334

2022-10-21 21:58 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:80083fb4a90e4659daf2c1f4bced95612b502040

2022-10-21 22:01 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:54b5114701694111732a9dffb69e2afafc37b54e

2022-10-21 22:09 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:fd67de25d6fb850799cd196a5fe88dc56f00fb6f

2022-10-21 22:13 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:589b226f95d4e3c03c25ad079d35e25c7946ff02

2022-10-21 22:18 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:025236066b39197eb8031ca1b2e2a92381458fdf

2022-10-21 22:40 UTC, Jaryt requested changes
Getting there! Please do a pass and check on `env_var_name` types

2022-10-21 22:40 UTC, Jaryt commented on src/scripts/ecr-login.sh
> +ORB_VAL_ACCOUNT_URL="${!ORB_EVAL_REGISTRY_ID}.dkr.ecr.${ORB_EVAL_REGION}.amazonaws.com"
```suggestion
ORB_VAL_ACCOUNT_URL="${!ORB_ENV_REGISTRY_ID}.dkr.ecr.${ORB_EVAL_REGION}.amazonaws.com"
```

2022-10-21 22:40 UTC, Jaryt commented on src/commands/ecr-login.yml
> +              ORB_VAL_REGISTRY_ID: <<parameters.registry-id>>
```suggestion
              ORB_ENV_REGISTRY_ID: <<parameters.registry-id>>
```

For parameters type of `env_var_name` the prefix should be `ORB_ENV_`. This indicates later on that you should indirectly reference the environment variable.

2022-10-21 22:54 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:fd37e3ee01ce0fe84e76f0872ad0356105a71f40

2022-10-21 22:54 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:041f955fe36eda96f9e9079e2392ac073fe6e944

2022-10-21 23:03 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:5422f5a0077dd6e449b5a55f0cd15cbfcf78ebba

2022-10-22 00:30 UTC, Jaryt approved these changes
Good work!

2022-10-22 00:46 UTC, merged

2022-10-24 10:59 UTC, JeroenRijks commented
Hi, when will this PR make it into a published version of the orb? My org is currently having issues caused by the https://github.com/CircleCI-Public/aws-ecr-orb/issues/227 bug - if this could get released as 8.1.4, that would be really useful!

2022-10-25 13:07 UTC, Jedv-TransReport commented
> Hi, when will this PR make it into a published version of the orb? My org is currently having issues caused by the #227 bug - if this could get released as 8.1.4, that would be really useful!

I second this! Really needed.