feat: implement circleci env subst
CircleCI-Public/aws-ecr-orb pull request #274
Opened 2023-06-07 06:42 UTC by brivu

This `PR` replaces `eval` with `circleci env subst`. It also updates all variable names to follow the Orb Standardization Guide.

2023-06-07 15:33 UTC, KyleTryon requested changes

2023-06-07 15:33 UTC, KyleTryon commented on src/commands/build-image.yml
> +        ORB_EVAL_PLATFORM: <<parameters.platform>>
These are not evaluated, they are normal VAL, all `env subst` is VAL

2023-06-14 18:45 UTC, EricRibeiro approved these changes

2023-06-15 01:00 UTC, KyleTryon approved these changes

2023-06-15 04:54 UTC, merged