refactor!: orb tools 12 migration
CircleCI-Public/aws-ecr-orb pull request #275
Opened 2023-06-07 15:37 UTC by brivu

## Description

This `PR` updates the `AWS ECR` Orb to the new major version of Orb Tools. As it contains breaking changes, several modifications were unnecessary to move from v11 to [v12](https://circleci.com/developer/orbs/orb/circleci/orb-tools). 

## Changes

1. All parameters and commands containing dashes have been converted to the new snake case standard (replace `-` with `_`).
2. The comprehensive list of changes can be found below.

### Changes in `.circleci/config.yml`:

1. Update the orb-tools version from 11.6 to 12.0.
1. Move the job requirement list from `orb-tools/publish` to `orb-tools/continue`.
1. Remove the `orb-tools/publish` job since development versions are no longer necessary.
1. Add the new `orb_name` parameter in `orb-tools/continue`.
1. Rename the `orb-tools/continue` job parameters to comply with the new snake case standard.
   - `orb_name`, `pipeline_number` and `vcs_type`.

### Changes in `.circleci/test-deploy.yml`:

1. Update the orb-tools version from `11.6` to `12.0`.
1. Remove the `aws-cli: circleci/aws-cli@dev:<<pipeline.git.revision>>` line, and replace it with `aws-cli: {}`.
1. Remove the `orb-tools/lint`, `orb-tools/pack`, and `orb-tools/review` jobs. ⚠️ 
1. Rename the `orb-tools/publish` job parameters to comply with the new snake case standard.
   - `orb_name`, `vcs_type`, `pub_type`, `enable_pr_comment` and `github_token`.
1. Change the `orb-tools/pack` filter to trigger only on tagged releases.

2023-06-14 19:01 UTC, EricRibeiro requested changes

2023-06-15 05:05 UTC, brivu commented on src/executors/default.yml
> +  use_docker_layer_caching:
Good catch, changed to `resource_class`.

2023-06-15 05:05 UTC, brivu commented on src/commands/tag_image.yml
> +        ORB_EVAL_TARGET_TAG: <<parameters.target_tag>>
Good catch, changed to `STR`

2023-06-15 17:11 UTC, EricRibeiro requested changes

2023-06-15 17:11 UTC, EricRibeiro commented on src/scripts/tag_image.sh
> +MANIFEST=$(aws ecr batch-get-image --repository-name "${ORB_STR_REPO}" --image-ids imageTag="${ORB_STR_SOURCE_TAG}" --query 'images[].imageManifest' --output text)
```suggestion
MANIFEST="$(aws ecr batch-get-image --repository-name "${ORB_STR_REPO}" --image-ids imageTag="${ORB_STR_SOURCE_TAG}" --query 'images[].imageManifest' --output text)"
```

2023-06-15 18:09 UTC, EricRibeiro approved these changes

2023-06-15 19:39 UTC, merged