feat: repository encryption parameter
CircleCI-Public/aws-ecr-orb pull request #289
Opened 2023-07-21 15:06 UTC by brivu

This `PR` adds the `--encryption-configuration` parameter to the `aws ecr create-repository` command, enabling users to set the ECR repo encryption while the repository is being set up.

2023-07-25 09:46 UTC, fruit commented on src/scripts/create_repo.sh
> +ORB_STR_ENCRYPTION_KMS_KEY="$(circleci env subst "${ORB_STR_ENCRYPTION_KMS_KEY}")"
This 2 lines are duplicated - already exists on 12-13 lines

2023-07-25 09:53 UTC, fruit commented on src/scripts/create_repo.sh
> +ORB_STR_ENCRYPTION_KMS_KEY="$(circleci env subst "${ORB_STR_ENCRYPTION_KMS_KEY}")"
Given 2 lines are exists on 12-13 lines. Remove them here, or remove them from 12-13 lines.

```suggestion
```

2023-07-26 18:31 UTC, EricRibeiro requested changes

2023-07-26 18:31 UTC, EricRibeiro commented on src/scripts/create_repo.sh
> +    if [ "$ORB_BOOL_REPO_SCAN_ON_PUSH" != "1" ]; then
```suggestion
    if [ "$ORB_BOOL_REPO_SCAN_ON_PUSH" -ne 1 ]; then
```

2023-07-26 18:31 UTC, EricRibeiro commented on src/scripts/create_repo.sh
> +ORB_ENUM_ENCRYPTION_TYPE="$(circleci env subst "${ORB_ENUM_ENCRYPTION_TYPE}")"
`enum` is a static string. There is no need to expand it.

2023-07-26 18:44 UTC, brivu commented on src/scripts/create_repo.sh
> +    if [ "$ORB_BOOL_REPO_SCAN_ON_PUSH" != "1" ]; then
changed in latest commit

2023-07-26 22:04 UTC, EricRibeiro approved these changes

2023-07-26 22:09 UTC, merged